export const FILIAIS = [
  { codigo: 'ACC', nome: 'DO VALLE TRANBSPORTES' },
  { codigo: 'ACT', nome: 'ACCERT TRANSPORTES E LOG LTDA' },
  { codigo: 'AER', nome: 'AEREO - RS - VITORIA - POA' },
  { codigo: 'AMB', nome: 'MELLO E ZIGOWSKI LTDA' },
  { codigo: 'ANA', nome: 'THIAGO TRANSPORTES' },
  { codigo: 'ANP', nome: 'EP TRANSPORTES E CARGAS LTDA' },
  { codigo: 'APT', nome: 'APT LOGISTICA ARM. E TRANSPORT' },
  { codigo: 'ARG', nome: 'ARAGUAINA-TO VITORIA' },
  { codigo: 'ARM', nome: 'BELIZARIO TRANSPORTES ME' },
  { codigo: 'ARQ', nome: 'ARIQUEMES -RO RAPIDAO RONDONIA' },
  { codigo: 'AUX', nome: 'ARAGUAINA - TRANSUL ENC LTDA' },
  { codigo: 'BEL', nome: 'BELEM - PA - VITORIA' },
  { codigo: 'BGA', nome: 'ALT - TRANSPORTES - BGA' },
  { codigo: 'BLF', nome: 'W2 TRANSPORTES LTDA' },
  { codigo: 'BLT', nome: 'NORTE BRASIL' },
  { codigo: 'BNU', nome: 'BLUMENAU - VITORIA PROV LTDA' },
  { codigo: 'BRG', nome: 'VITORIA - BIRIGUI - SP' },
  { codigo: 'BSB', nome: 'BRASILIA - DF - VITORIA' },
  { codigo: 'BVB', nome: 'BOA VISTA - RR - H C TRANSPORT' },
  { codigo: 'CAR', nome: 'TRANSPORTADORA CARDOSO LTDA' },
  { codigo: 'CCL', nome: 'CACOAL-RO-RAPIDAO RONDONIA' },
  { codigo: 'CCX', nome: 'ALT BRASIL TRANSPORTES' },
  { codigo: 'CGK', nome: 'KM TRANSPORTES' },
  { codigo: 'CGR', nome: 'VITORIA PROVEDORA LOGISTICA LTDA' },
  { codigo: 'CLC', nome: 'CLC LOGISTICA E TRANSPORTE LDT' },
  { codigo: 'COG', nome: 'COGO TRANSPORTES' },
  { codigo: 'CON', nome: 'CONTAGEM - VITORIA - MG' },
  { codigo: 'COR', nome: 'VITORIA PROVEDORA LOGISTICA LT' },
  { codigo: 'CPD', nome: 'PREST CONST E TRANSP IX TRANSP' },
  { codigo: 'CTL', nome: 'ANTISA PRESTADORA DE SERVICOS' },
  { codigo: 'CWB', nome: 'CURITIBA - VITORIA PROV LTDA' },
  { codigo: 'CXS', nome: 'CAXIAS DO SUL - RS - VITORIA' },
  { codigo: 'DLL', nome: 'DL LOGISTICA LTDA' },
  { codigo: 'DOU', nome: 'VITORIA PROVEDORA - DOURADOS' },
  { codigo: 'EDF', nome: 'ACCERT TRANSPORTE E LOGISTICA' },
  { codigo: 'EGO', nome: 'EXPRESSO GOIAS E LOGISTICA LTD' },
  { codigo: 'EGP', nome: 'BARQUEIROS MAU' },
  { codigo: 'ENT', nome: 'EXPRESSO NOVA TRES LAGOAS LTDA' },
  { codigo: 'EPT', nome: 'E P TRANSPORTES DE CARGAS LTDA' },
  { codigo: 'EVT', nome: 'ALTAMIRA - PA - NORTE BRASIL' },
  { codigo: 'EXT', nome: 'EXTREMA - VITLOG' },
  { codigo: 'FLN', nome: 'FLORIANOPOLIS - VITORIA PROVED' },
  { codigo: 'FOR', nome: 'FORTALEZA - CE - VITORIA' },
  { codigo: 'FRC', nome: 'VITORIA - FRANCA - SP' },
  { codigo: 'FRP', nome: 'FREI PAULO - SE - VITORIA' },
  { codigo: 'FRT', nome: 'FROTA' },
  { codigo: 'FSA', nome: 'VITORIA PROVEDORA LOGISTICA' },
  { codigo: 'FTG', nome: 'VITLOG FROTA GYN' },
  { codigo: 'FTM', nome: 'VITLOG FROTA MATRIZ' },
  { codigo: 'GET', nome: 'L C ENCOMENDAS E CARGAS LTDA' },
  { codigo: 'GIT', nome: 'RAPIDO IPORA TRANSP LOG LTDA' },
  { codigo: 'GJM', nome: 'GUAJARA MIRIM- VITORIA LOGISTI' },
  { codigo: 'GO5', nome: 'POOL G5' },
  { codigo: 'GOD', nome: 'GO - TRANSP DO VALLE LTDA' },
  { codigo: 'GOI', nome: 'GOIAS INTERIOR' },
  { codigo: 'GOR', nome: 'INVICTA TRANSPORTES EIRELI' },
  { codigo: 'GOT', nome: 'GO TRANSPORTES E ENCOMENDAS LT' },
  { codigo: 'GOU', nome: 'ALL CARGO LOG E TRANSP' },
  { codigo: 'GRP', nome: 'GURUPI - TRANSUL ENC LTDA' },
  { codigo: 'GRS', nome: 'CEC FERREIRA TRANSPORTES LTDA' },
  { codigo: 'GRT', nome: 'W J DA SILVA RAPIDO TRANSSILVA' },
  { codigo: 'GSL', nome: 'C & C FER TRANSP LT-RAP.SUDOES' },
  { codigo: 'GST', nome: 'ADEMIR GUERINI (VITLOG)' },
  { codigo: 'GYN', nome: 'GOIANIA - GO - VITORIA' },
  { codigo: 'HCS', nome: 'HCS MOTA E CIA LTDA' },
  { codigo: 'HGY', nome: 'HUB VITLOG' },
  { codigo: 'IDL', nome: 'IDEAL SERVICOS E TRANSPORTES L' },
  { codigo: 'IMP', nome: 'IMPERATRIZ - VITLOG' },
  { codigo: 'IPO', nome: 'DL LOGISTICA LTDA' },
  { codigo: 'ITI', nome: 'VITLOG TRANSPORTES' },
  { codigo: 'ITN', nome: 'VITORIA PROVEDORA LOGISTICA' },
  { codigo: 'JAS', nome: 'JA E SOUZA TRANS LOG' },
  { codigo: 'JCL', nome: 'JCL TRANSPORTE E LOGISTICA' },
  { codigo: 'JGS', nome: 'JARAGUA DO SUL - VITORIA PROV' },
  { codigo: 'JJC', nome: 'JJCG LOGISTICA LTDA' },
  { codigo: 'JN1', nome: 'TRANSETE TRANSPORTES SEGURO LT' },
  { codigo: 'JNA', nome: 'VVIACAO JUINA' },
  { codigo: 'JOI', nome: 'VITORIA - JOINVILLE - SC' },
  { codigo: 'JPR', nome: 'JI PARANA - RAPIDAO RONDONIA' },
  { codigo: 'LAM', nome: 'LA TRANSOPORTES' },
  { codigo: 'LAT', nome: 'LA TRANSOPORTES' },
  { codigo: 'LCO', nome: 'OPCAO TRANSPORTES LTDA' },
  { codigo: 'LCV', nome: 'TRANSRAPIDO SINAL VERDE' },
  { codigo: 'LDB', nome: 'VITORIA PROVEDORA LOGISTICA LT' },
  { codigo: 'LJD', nome: 'LAJEADO - VITORIA PROV LTDA' },
  { codigo: 'MAB', nome: 'MARABA' },
  { codigo: 'MAO', nome: 'MANAUS - AM -' },
  { codigo: 'MCP', nome: 'MACAPA - TMD DISTRIB TRANSP DE' },
  { codigo: 'MTZ', nome: 'MATRIZ - RS - VITORIA' },
  { codigo: 'MVC', nome: 'MVCOUTO GESTAO DE NEGOCIOS LTD' },
  { codigo: 'NCX', nome: 'ROTA TRANSPORTES E LOG' },
  { codigo: 'NEG', nome: 'NWF TRANSPORTES E LOGISTICA' },
  { codigo: 'NHO', nome: 'NOVO HAMBURGO - RS - VITORIA' },
  { codigo: 'NMT', nome: 'TRANSRAPIDO SINAL VERDE' },
  { codigo: 'NQL', nome: 'CW3 TRANSP E LOG LTDA' },
  { codigo: 'NVS', nome: 'NOVA SERRANA - MG' },
  { codigo: 'OPF', nome: 'EXPRESSO ARBA TRANSPORTES ME' },
  { codigo: 'PAL', nome: 'SOUZA PIRES TRANSPORTES' },
  { codigo: 'PBA', nome: 'EXPRESSO SULMATOGROSSENSE LTDA' },
  { codigo: 'PER', nome: 'PERMUTA' },
  { codigo: 'PLM', nome: 'PALMAS - TRANSUL ENC LTDA' },
  { codigo: 'PMW', nome: 'VITORIA PROVEDORA - PALMAS -TO' },
  { codigo: 'POA', nome: 'PORTO ALEGRE - RS - VITORIA' },
  { codigo: 'PPY', nome: 'POUSO ALEGRE - VITORIA' },
  { codigo: 'PRL', nome: 'ALT - TRANSPORTES - ROO' },
  { codigo: 'PVH', nome: 'VITORIA PROVEDORA LOGISTICA LT' },
  { codigo: 'PVV', nome: 'PORTO VELHO - RO - RODA VIVA' },
  { codigo: 'RBV', nome: 'RIO BRANCO - AC - RODAVIVA' },
  { codigo: 'RCH', nome: 'GOLD BRANCO LOG TRANSP EIRELI' },
  { codigo: 'REA', nome: 'R&A TRANQPORTES' },
  { codigo: 'RED', nome: 'REDENCAO - PA' },
  { codigo: 'ROO', nome: 'VITLOG TRANSPORTES' },
  { codigo: 'RVD', nome: 'TOP LUZ TRANS LOG SERV LTDA ME' },
  { codigo: 'SAL', nome: 'SARA TRANSPORTES E LOG LTDA' },
  { codigo: 'SAR', nome: 'SARA TRANSPORTES E LOGISTICA L' },
  { codigo: 'SAT', nome: 'NORTE LOG TRANSPORTES' },
  { codigo: 'SCX', nome: 'VIACAO XAVANTE LTDA' },
  { codigo: 'SCZ', nome: 'VITORIA PROVED LOGISTICA LTDA' },
  { codigo: 'SEN', nome: 'SENE TRANPORTE E CARGAS LTDA' },
  { codigo: 'SLZ', nome: 'SAO LUIZ - VITLOG' },
  { codigo: 'SNP', nome: 'VITLOG TRANSPORTES LTDA' },
  { codigo: 'SOA', nome: 'UNITRANSP' },
  { codigo: 'SOB', nome: 'SOBRAL - CE - VITORIA' },
  { codigo: 'SPO', nome: 'SAO PAULO - VITORIA PROV LTDA' },
  { codigo: 'SRS', nome: 'VITLOG TRANSPORTES LTDA' },
  { codigo: 'STI', nome: 'SANTA INEZ VITLOG' },
  { codigo: 'STM', nome: 'SANTAREM - PA - VITORIA' },
  { codigo: 'SUL', nome: 'CRUZEIRO DO SUL' },
  { codigo: 'TAQ', nome: 'VITLOG TRANSPORTES' },
  { codigo: 'TBR', nome: 'TUBARAO - VITORIA PROVEDORA' },
  { codigo: 'TGY', nome: 'TRANSUL ENCOMENDAS - GYN' },
  { codigo: 'TIN', nome: 'GOIATINS TRANSPORTES' },
  { codigo: 'TLS', nome: 'TRES LAGOAS - VITORIA PROV LTD' },
  { codigo: 'TNM', nome: 'TNM PROVEDORA LOGISTICA LTDA' },
  { codigo: 'TRL', nome: 'TRL TRANSP ROD CARGAS LTDA' },
  { codigo: 'UDI', nome: 'VITLOG UBERLANDIA - MG' },
  { codigo: 'UTR', nome: 'USE TRANSPORTES E LOGISTICA' },
  { codigo: 'VDC', nome: 'VITORIA DA CONQUISTA- BA' },
  { codigo: 'VHN', nome: 'VILHENA - RO - J L DOS SANTOS' },
  { codigo: 'VIX', nome: 'VIANA - ES - VITORIA' },
  { codigo: 'VLH', nome: 'VITORIA - VILHENA' },
  { codigo: 'VTP', nome: 'VITLOG PATRIMONIAL LTDA' },
  { codigo: 'VZG', nome: 'VITORIA PROVEDORA LOGISTICA LT' },
  { codigo: 'XAP', nome: 'VITORIA PROVEDORA LOGISTICA LT' },
  { codigo: 'YAN', nome: 'YANO TRANSPORTES RODOVIARIOS L' },
]

const filialMap = Object.fromEntries(FILIAIS.map(f => [f.codigo, f.nome]))

export function getNomeFilial(codigo) {
  return filialMap[codigo] || codigo
}
