// Códigos de ocorrência SSW
export const OCORRENCIAS = [
  { codigo: '01', descricao: 'ENTREGA REALIZADA' },
  { codigo: '04', descricao: 'DESTINATARIO RETIRA' },
  { codigo: '08', descricao: 'DEST ALEGA MERC EM DESACORDO' },
  { codigo: '09', descricao: 'DESTINATARIO AUSENTE/FECHADO' },
  { codigo: '10', descricao: 'ENDER DESTINAT NAO LOCALIZADO/MODIFICADO' },
  { codigo: '12', descricao: 'REIMPRESSAO DE ETIQUETAS' },
  { codigo: '13', descricao: 'ENTREGA PREJUDICADA P/HORARIO' },
  { codigo: '14', descricao: 'AGUARDANDO AGENDAMENTO DO CLIENTE' },
  { codigo: '15', descricao: 'ENTREGA AGENDADA PELO CLIENTE' },
  { codigo: '16', descricao: 'VEICULO RETIDO NOS POSTOS FISCAIS' },
  { codigo: '17', descricao: 'ENTREGUE COM RESSALVAS' },
  { codigo: '18', descricao: 'VEICULO COM FALHA MECANICA' },
  { codigo: '19', descricao: 'FALTA DE ESPACO FISICO DEPOSITO DESTINATARIO' },
  { codigo: '21', descricao: 'REENTREGA SOLICITADA PELO CLIENTE' },
  { codigo: '23', descricao: 'VEICULO LIBERADO DO POSTO FISCAL' },
  { codigo: '24', descricao: 'MERCADORIA DEVOLVIDA AO PARCEIRO' },
  { codigo: '25', descricao: 'MERCADORIA RETIDA ATE SEGUNDA ORDEM' },
  { codigo: '27', descricao: 'EXCESSO DE VEICULOS NO LOCAL DE ENTREGA' },
  { codigo: '31', descricao: 'AGUARDANDO REFATURAMENTO DA MERCADORIA' },
  { codigo: '34', descricao: 'REENTREGA AUTORIZADA' },
  { codigo: '35', descricao: 'DEVOLUCAO AUTORIZADA' },
  { codigo: '36', descricao: 'REFATURAMENTO P/ OUTRO DESTINA' },
  { codigo: '37', descricao: 'PALETIZACAO' },
  { codigo: '38', descricao: 'CTRC RETIDO PARA CONFERENCIA' },
  { codigo: '39', descricao: 'SEPARACAO DE MERCADORIA' },
  { codigo: '41', descricao: 'ENTREGA TROCADA' },
  { codigo: '43', descricao: 'DATA CHEGADA NO PORTO' },
  { codigo: '44', descricao: 'CLIENTE BLOQUEADO' },
  { codigo: '45', descricao: 'COBRAR ARMAZENAMENTO (GRENDENE)' },
  { codigo: '46', descricao: 'INICIO DE ARMAZENAGEM' },
  { codigo: '48', descricao: 'FINAL DA ARMAZENAGEM' },
  { codigo: '49', descricao: 'SEM COBRANCA DE ARMAZENAGEM' },
  { codigo: '50', descricao: 'FALTA/EXTRAVIO TOTAL DE MERCADORIA' },
  { codigo: '51', descricao: 'SOBRA DE MERCADORIA' },
  { codigo: '52', descricao: 'FALTA DE DOCUMENTACAO' },
  { codigo: '53', descricao: 'AVARIA PARCIAL' },
  { codigo: '54', descricao: 'EMBALAGEM AVARIADA - IMAGENS' },
  { codigo: '57', descricao: 'CORTE CLIENTE' },
  { codigo: '58', descricao: 'DATA SAIDA DO PORTO' },
  { codigo: '60', descricao: 'MERCAD RETIDA FISCALIZACAO / GEROU TERMO' },
  { codigo: '61', descricao: 'FALTA/EXTRAVIO PARCIAL DE MERCADORIA' },
  { codigo: '62', descricao: 'AVARIA TOTAL' },
  { codigo: '63', descricao: 'GREVE' },
  { codigo: '64', descricao: 'MERC.ENTREGUE P/REDESPACHO' },
  { codigo: '65', descricao: 'MERCADORIA LIBERADA NO FISCO / TERMO PAGO' },
  { codigo: '66', descricao: 'RODOVIA COM ACESSO INTERROMPID' },
  { codigo: '67', descricao: 'OCORRENCIA ANTERIOR INDEVIDA' },
  { codigo: '68', descricao: 'ETIQUETAGEM (GRENDENE)' },
  { codigo: '69', descricao: 'ESTADIA' },
  { codigo: '70', descricao: 'VEICULO AGUARDANDO DESCARGA' },
  { codigo: '72', descricao: 'FENOMENOS DA NATUREZA' },
  { codigo: '74', descricao: 'VOLUME LOCALIZADO' },
  { codigo: '75', descricao: 'COBRAR AGENDAMENTO (GRENDENE)' },
  { codigo: '76', descricao: 'PENDENCIAS-RECIBO DE DESCARGA/DIARIA/CTE COMPLEM' },
  { codigo: '77', descricao: 'SEGUIU SOMENTE A DOCUMENTACAO' },
  { codigo: '79', descricao: 'FERIADO LOCAL' },
  { codigo: '82', descricao: 'ROUBO TOTAL DE MERCADORIA' },
  { codigo: '83', descricao: 'ROUBO PARCIAL DE MERCADORIA' },
  { codigo: '85', descricao: 'SINISTROS' },
  { codigo: '89', descricao: 'MERC.ENTREG NA BALCA AGUARD RETORNO P/BAIXA CTRC' },
  { codigo: '90', descricao: 'PENDENCIA SOLUCIONADA' },
  { codigo: '91', descricao: 'MERCADORIA EM INDENIZACAO' },
  { codigo: '92', descricao: 'MERCADORIA INDENIZADA' },
  { codigo: '93', descricao: 'CTRC EMIT P/EFEITO FRETE/ICMS' },
  { codigo: '94', descricao: 'EXPORTACAO PENDENTE E ARMAZENADA' },
  { codigo: '95', descricao: 'OPERACAO CANCELADA' },
]

export function getOcorrencia(codigo) {
  return OCORRENCIAS.find(o => o.codigo === codigo) || null
}
